# Site settings
title: "Juliette Kernion"
description: "Resume and Portfolio Site"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "resume"
    url: /jkernion_resume.pdf
  - title: "folio"
    url: /folio/
  - title: "linkedin"
    url: https://www.linkedin.com/in/jkernion/
  - title: "git"
    url: http://github.com/kernion
  - title: "about"
    url: /about
